<?xml version="1.0"?>
<!--
    - Base      : kobuki
    - Stacks    : hexagons
    - Telescopic: telescopic
    - 3d Sensor : orbbec
    - Laser		: urg04lx
    
-->    
<robot name="turtlebot" xmlns:xacro="http://ros.org/wiki/xacro">
	
  <xacro:property name="CAMERA_H" value="0.457" />
  <xacro:property name="FOOT_H" value="0.02" />
  
<!--
	- Distance from floot (base_footprint) to top_plate = 0.41 (41 cm)
	- Distance from base_link to top_plate = 0.3996 (39.96 cm)
	- Distance from middle plate to top plate = 0.2092 m (20.92 cm)
    - Distance from top_plate to telescopic_bar foot:
          pos 1: 0.197 m (19.7 cm)
          pos 2: 0.457 m (45.7 cm)
          pos 3: 0.725 m (72.5 cm)
          pos 4: 0.974 m (97.4 cm)
-->  

  <xacro:include filename="$(find turtlebot_description)/urdf/turtlebot_library.urdf.xacro" />
  
  <kobuki/>
  <stack_hexagons                 parent="base_link"/>
  <stack_bar				  	  parent="base_link"/>
  
  <sensor_orbbec_astra name="radio" parent="telescopic_foot_link">
      <origin xyz="0.02 0.011 ${2*FOOT_H-0.006}" rpy="0 0 0" />
  </sensor_orbbec_astra>
  
  <sensor_logitech_c920 prefix="rear" parent="telescopic_foot_link">
      <origin xyz="-0.02 0.011 0.049" rpy="0 0 0" />
  </sensor_logitech_c920>
   
  <sensor_hokuyo_urg04lx name="hokuyo" parent="base_link" >
		<origin xyz="0.137 0 0.241" rpy="0 0 0" /> 
   </sensor_hokuyo_urg04lx>
   
   <sensor_microphone_array name="radio" parent="plate_top_link" >
		<origin xyz="0.1 0 0.006" rpy="0 0 0" /> 
   </sensor_microphone_array>
  
   <!--screen name="radio" parent="plate_top_link" >
		<origin xyz="-0.03 0 0.05" rpy="0 -0.09 0" /> 
   </screen-->

</robot>
